name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-22.04
    outputs:
      commit_msg: ${{ steps.check_skip.outputs.commit_msg }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check commit message
        id: check_skip
        run: |
          echo "commit_msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Install and build frontend
        run: |
          cd client
          npm install
          npm run lint
          npm run build

      - name: Move frontend build to backend
        run: |
          rm -rf server/dist
          cp -r client/dist server/

      - name: Install backend dependencies
        run: |
          cd server
          npm install
          npm run lint

      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(steps.check_skip.outputs.commit_msg, '#skip') }}
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && !contains(needs.deployment_pipeline.outputs.commit_msg, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify_success:
    needs: [deployment_pipeline]
    if: ${{ success() && github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Notify Discord of success
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            Deployment successful for commit: ${{ github.sha }} by ${{ github.event.head_commit.author.name }}
            Live site: https://phonebook-app-uyb0.onrender.com

  notify_failure:
    needs: [deployment_pipeline]
    if: ${{ failure() && github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Notify Discord of failure
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            Build failed!
            Commit: ${{ github.event.head_commit.url }}
            Message: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
